# Generated by Selenium IDE
import time
from selenium import webdriver
# import Chrome options
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
# import webdriver_manager


def main():
  #add headless argument to chome
  paste = input("Paste: ")
  paste = paste.lower()
  #replace any number with "NUMBER"
  paste = paste.replace("0", "NUMBER")
  paste = paste.replace("1", "NUMBER")
  paste = paste.replace("2", "NUMBER")
  paste = paste.replace("3", "NUMBER")
  paste = paste.replace("4", "NUMBER")
  paste = paste.replace("5", "NUMBER")
  paste = paste.replace("6", "NUMBER")
  paste = paste.replace("7", "NUMBER")
  paste = paste.replace("8", "NUMBER")
  paste = paste.replace("9", "NUMBER")
  # only allow a-z ,. and " "
  paste = paste.replace("!", "")
  paste = paste.replace("?", "")
  paste = paste.replace("'", "")
  paste = paste.replace("#", "")
  paste = paste.replace("&", "")
  paste = paste.replace("$", "")
  paste = paste.replace("%", "")
  paste = paste.replace("^", "")
  paste = paste.replace("*", "")
  paste = paste.replace("(", "")
  paste = paste.replace(")", "")
  paste = paste.replace("-", "")
  paste = paste.replace("+", "")
  paste = paste.replace("=", "")
  paste = paste.replace("[", "")
  paste = paste.replace("]", "")
  paste = paste.replace("{", "")
  paste = paste.replace("}", "")
  paste = paste.replace("|", "")
  paste = paste.replace("\\", "")
  paste = paste.replace(";", "")
  paste = paste.replace(":", "")
  paste = paste.replace("<", "")
  paste = paste.replace(">", "")
  title = input("Title: ")
  
  #apply the same formatting to title as to paste
  title = title.lower()
  title = title.replace("0", "NUMBER")
  title = title.replace("1", "NUMBER")
  title = title.replace("2", "NUMBER")
  title = title.replace("3", "NUMBER")
  title = title.replace("4", "NUMBER")
  title = title.replace("5", "NUMBER")
  title = title.replace("6", "NUMBER")
  title = title.replace("7", "NUMBER")
  title = title.replace("8", "NUMBER")
  title = title.replace("9", "NUMBER")
  title = title.replace("!", "")
  title = title.replace("?", "")
  title = title.replace("'", "")
  title = title.replace("#", "")
  title = title.replace("&", "")
  title = title.replace("$", "")
  title = title.replace("%", "")
  title = title.replace("^", "")
  title = title.replace("*", "")
  title = title.replace("(", "")
  title = title.replace(")", "")
  title = title.replace("-", "")
  title = title.replace("+", "")
  title = title.replace("=", "")
  title = title.replace("[", "")
  title = title.replace("]", "")
  title = title.replace("{", "")
  title = title.replace("}", "")
  title = title.replace("|", "")
  title = title.replace("\\", "")
  title = title.replace(";", "")
  title = title.replace(":", "")
  title = title.replace("<", "")
  title = title.replace(">", "")

  chrome_options = Options()
  chrome_options.add_argument("--headless")
  driver = webdriver.Chrome(ChromeDriverManager().install(),options=chrome_options)

  driver.get("https://libraryofbabel.info/")
  driver.set_window_size(1600, 900)
  driver.find_element(By.ID, "permutable2").click()
  driver.find_element(By.ID, "find").send_keys(f"{paste}")
  driver.find_element(By.ID, "button").click()
  driver.find_element(By.XPATH, "//a").click()
  driver.find_element(By.LINK_TEXT, "Bookmarkable").click()
  alert = driver.switch_to.alert
  alert.send_keys(f"{title}")
  alert.accept()
  # get url
  time.sleep(5)
  url = driver.current_url
  print(url)

main()